# Generated by Django 5.2.8 on 2025-12-20 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('ale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ale_date', models.DateTimeField()),
                ('ale_repeat', models.CharField(max_length=10)),
            ],
        ),
    ]
