# Generated by Django 5.2.8 on 2025-12-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='ale_repeat',
            field=models.CharField(max_length=20),
        ),
    ]
