# Generated by Django 5.2.8 on 2026-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('scp_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('scp_description', models.CharField(max_length=255)),
                ('scp_identifier_code', models.CharField(max_length=100)),
                ('scp_type', models.CharField(choices=[('Task', 'Task'), ('User', 'User')], editable=False)),
            ],
        ),
    ]
