# Generated by Django 5.2.8 on 2025-11-21 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('per_app_id', models.UUIDField(default=uuid.UUID('851896d7-e860-451d-9cb6-aa94483ee20a'), editable=False, primary_key=True, serialize=False)),
                ('per_app_task_notification', models.BooleanField(default=False)),
                ('per_app_calendar_home', models.BooleanField(default=False)),
                ('per_app_task_email_notification', models.BooleanField(default=False)),
                ('per_app_open_apps', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('use_id', models.UUIDField(default=uuid.UUID('eba83a94-2ffb-468a-b0d4-fc964da78401'), editable=False, primary_key=True, serialize=False)),
                ('use_name', models.CharField()),
                ('use_status', models.CharField(choices=[('A', 'ACTIVATE'), ('B', 'BLOCKED'), ('D', 'DEACTIVATE')])),
                ('use_email', models.CharField(unique=True)),
                ('use_password_hash', models.CharField(null=True)),
                ('use_phone', models.CharField(max_length=20, null=True)),
                ('use_login_type', models.CharField()),
                ('use_ip_address', models.CharField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(related_name='users', to='User.permission')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.UUID('9c05693d-9370-41ae-9a85-486f445be9b1'), editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(editable=False, max_length=30)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_endpoint', models.CharField(editable=False, max_length=30)),
                ('log_description', models.TextField(editable=False)),
                ('fk_log_use_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
