# Generated by Django 5.2.8 on 2025-11-21 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='log_id',
            field=models.UUIDField(default=uuid.UUID('e71a7054-05f7-4d79-847f-1c7059306e61'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='per_app_id',
            field=models.UUIDField(default=uuid.UUID('5128c40b-336f-48f5-8cbd-b25366e3a142'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_id',
            field=models.UUIDField(default=uuid.UUID('96a74a32-7d85-4f1b-8d56-6a5d983adda7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
