# Generated by Django 5.2.8 on 2026-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_google_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
