# Generated by Django 5.2.8 on 2025-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_status',
            field=models.CharField(choices=[('A', 'ACTIVATE'), ('B', 'BLOCKED'), ('D', 'DEACTIVATE')], max_length=10),
        ),
    ]
