# Generated by Django 5.2.8 on 2026-02-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_use_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_avatar',
            field=models.CharField(default=''),
        ),
    ]
