# Generated by Django 5.2.8 on 2025-12-03 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_changelog_log_id_alter_permission_per_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='log_id',
            field=models.UUIDField(default=uuid.UUID('3a3dba32-f3c7-4122-8500-59a05f618adc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='per_app_id',
            field=models.UUIDField(default=uuid.UUID('80246a05-698e-46ab-a9ae-27257ace947b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_id',
            field=models.UUIDField(default=uuid.UUID('f2c6e57d-b214-4efe-be8c-a4981206ba49'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
