# Generated by Django 5.2.8 on 2026-02-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_use_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
