# Generated by Django 5.2.8 on 2026-01-07 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sta_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sta_name', models.CharField(max_length=10, unique=True)),
                ('fk_sta_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
