# Generated by Django 5.2.8 on 2026-03-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
        ('TaskRoles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_tts_tsk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
                ('fk_tts_tsr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskRoles.taskroles')),
                ('fk_tts_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fk_tts_use_id', 'fk_tts_tsr_id', 'fk_tts_tsk_id'), name='unique_user_task_role')],
            },
        ),
    ]
