# Generated by Django 5.2.8 on 2026-01-07 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLists',
            fields=[
                ('che_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('che_name', models.CharField(max_length=30)),
                ('che_status', models.CharField(choices=[('CONCLUDE', 'Conclude'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled')])),
                ('che_date', models.DateTimeField()),
                ('fk_che_tsk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task')),
            ],
        ),
    ]
