# Generated by Django 5.2.8 on 2026-02-12 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLists',
            fields=[
                ('che_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('che_name', models.CharField(max_length=30)),
                ('che_status', models.CharField(choices=[('CONCLUDE', 'Conclude'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled')])),
                ('che_date', models.DateTimeField()),
                ('che_description', models.CharField()),
                ('fk_che_tsk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Task.task')),
                ('fk_che_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
