# Generated by Django 5.2.8 on 2026-01-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='fk_che_tsk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
