# Generated by Django 5.2.8 on 2026-01-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0002_alter_checklists_fk_che_tsk_id'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='fk_che_tsk_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Task.task'),
        ),
    ]
