# Generated by Django 5.2.8 on 2026-01-07 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksAssociates',
            fields=[
                ('asc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asc_name', models.CharField(null=True, unique=True)),
                ('asc_link_reference', models.TextField(unique=True)),
                ('asc_type', models.CharField(max_length=10)),
                ('asc_icon', models.TextField(null=True)),
                ('fk_asc_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
