# Generated by Django 5.2.8 on 2025-12-20 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LinksAssociates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksAssociates',
            fields=[
                ('asc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asc_name', models.CharField(null=True, unique=True)),
                ('asc_link_reference', models.TextField(unique=True)),
                ('asc_type', models.CharField(max_length=10)),
                ('asc_icon', models.TextField(null=True)),
            ],
        ),
    ]
