# Generated by Django 5.2.8 on 2025-12-31 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerts', '__first__'),
        ('Labels', '__first__'),
        ('LinksAssociates', '__first__'),
        ('Status', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsk_title', models.CharField(max_length=30)),
                ('tsk_description', models.TextField()),
                ('tsk_status', models.CharField(max_length=20)),
                ('tsk_recurrence', models.CharField(max_length=10)),
                ('tsk_recurrence_end_in', models.DateTimeField()),
                ('tsk_conclude_expected_at', models.DateTimeField()),
                ('tsk_conclude_at', models.DateTimeField()),
                ('tsk_background', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('associateLinks', models.ManyToManyField(blank=True, to='LinksAssociates.linksassociates')),
                ('fk_tsk_ale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alerts.alerts')),
                ('fk_tsk_sta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Status.status')),
                ('fk_tsk_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, to='Labels.labels')),
            ],
        ),
    ]
