# Generated by Django 5.2.8 on 2026-01-17 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerts', '0001_initial'),
        ('Labels', '0001_initial'),
        ('LinksAssociates', '0001_initial'),
        ('Status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsk_title', models.CharField(max_length=30, unique=True)),
                ('tsk_description', models.TextField()),
                ('tsk_recurrence', models.CharField(max_length=10, null=True)),
                ('tsk_recurrence_end_in', models.DateTimeField(null=True)),
                ('tsk_conclude_expected_at', models.DateTimeField(null=True)),
                ('tsk_conclude_at', models.DateTimeField(null=True)),
                ('tsk_background', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('fk_tsk_ale_id', models.ManyToManyField(blank=True, to='Alerts.alerts')),
                ('fk_tsk_asc_id', models.ManyToManyField(blank=True, to='LinksAssociates.linksassociates')),
                ('fk_tsk_lab_id', models.ManyToManyField(blank=True, to='Labels.labels')),
                ('fk_tsk_sta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Status.status')),
                ('fk_tsk_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
