# Generated by Django 5.2.8 on 2025-12-13 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('ale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ale_date', models.DateTimeField()),
                ('ale_repeat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('lab_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksAssociates',
            fields=[
                ('asc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asc_name', models.CharField(null=True, unique=True)),
                ('asc_link_reference', models.TextField(unique=True)),
                ('asc_type', models.CharField(max_length=10)),
                ('asc_icon', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsk_title', models.CharField(max_length=30)),
                ('tsk_description', models.TextField()),
                ('tsk_status', models.CharField(max_length=20)),
                ('tsk_recurrence', models.CharField(max_length=10)),
                ('tsk_conclude_expected_at', models.DateTimeField()),
                ('tsk_conclude_at', models.DateTimeField()),
                ('tsk_background', models.CharField(max_length=15)),
                ('tsk_is_running', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('associateLinks', models.ManyToManyField(to='Task.linksassociates')),
                ('fk_tsk_ale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.alerts')),
                ('fk_tsk_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(to='Task.labels')),
            ],
        ),
    ]
