# Generated by Django 5.2.8 on 2025-12-20 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerts', '0002_initial'),
        ('LinksAssociates', '0002_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLists',
            fields=[
                ('che_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('che_name', models.CharField(max_length=30)),
                ('che_status', models.CharField(choices=[('CONCLUDE', 'Conclude'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled')])),
                ('che_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tsk_title', models.CharField(max_length=30)),
                ('tsk_description', models.TextField()),
                ('tsk_status', models.CharField(max_length=20)),
                ('tsk_recurrence', models.CharField(max_length=10)),
                ('tsk_conclude_expected_at', models.DateTimeField()),
                ('tsk_conclude_at', models.DateTimeField()),
                ('tsk_background', models.CharField(max_length=15)),
                ('tsk_is_running', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('associateLinks', models.ManyToManyField(blank=True, to='LinksAssociates.linksassociates')),
                ('fk_tsk_ale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alerts.alerts')),
            ],
        ),
    ]
