# Generated by Django 5.2.8 on 2025-11-21 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
        ('User', '0003_alter_changelog_log_id_alter_permission_per_app_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('ale_id', models.UUIDField(default=uuid.UUID('87ae6b2b-3710-441c-9e9d-be7a927352b4'), editable=False, primary_key=True, serialize=False)),
                ('ale_date', models.DateTimeField()),
                ('ale_repeat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('lab_id', models.UUIDField(default=uuid.UUID('833c9806-f825-4b0a-9ba1-0a0f9d205574'), editable=False, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksAssociates',
            fields=[
                ('asc_id', models.UUIDField(default=uuid.UUID('e67e8472-e7e0-4703-b663-7b1b76d515f3'), editable=False, primary_key=True, serialize=False)),
                ('asc_name', models.CharField(null=True, unique=True)),
                ('asc_link_reference', models.TextField(unique=True)),
                ('asc_type', models.CharField(max_length=10)),
                ('asc_icon', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tsk_id', models.UUIDField(default=uuid.UUID('02834b09-0429-4f2f-924d-681a01d46b1c'), editable=False, primary_key=True, serialize=False)),
                ('tsk_title', models.CharField(max_length=30)),
                ('tsk_description', models.TextField()),
                ('tsk_status', models.CharField(max_length=20)),
                ('tsk_recurrence', models.CharField(max_length=10)),
                ('tsk_conclude_expected_at', models.DateTimeField()),
                ('tsk_conclude_at', models.DateTimeField()),
                ('tsk_background', models.CharField(max_length=15)),
                ('tsk_is_running', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('associateLinks', models.ManyToManyField(to='Task.linksassociates')),
                ('fk_tsk_ale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.alerts')),
                ('fk_tsk_use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('labels', models.ManyToManyField(to='Task.labels')),
            ],
        ),
    ]
