# Generated by Django 5.2.8 on 2026-01-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tsk_conclude_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_conclude_expected_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_recurrence',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_recurrence_end_in',
            field=models.DateTimeField(null=True),
        ),
    ]
