# Generated by Django 5.2.8 on 2026-01-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0001_initial'),
        ('Status', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='associateLinks',
            new_name='fk_tsk_asc_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='labels',
            new_name='fk_tsk_lab_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fk_tsk_ale_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tsk_status',
        ),
        migrations.AddField(
            model_name='task',
            name='fk_tsk_alert_id',
            field=models.ManyToManyField(blank=True, to='Alerts.alerts'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='fk_tsk_sta_id',
        ),
        migrations.AddField(
            model_name='task',
            name='fk_tsk_sta_id',
            field=models.ManyToManyField(blank=True, to='Status.status'),
        ),
    ]
