# Generated by Django 5.2.8 on 2026-01-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_associatelinks_task_fk_tsk_asc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fk_tsk_alert_id',
            new_name='fk_tsk_ale_id',
        ),
    ]
