# Generated by Django 5.2.8 on 2025-12-03 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='ale_id',
            field=models.UUIDField(default=uuid.UUID('5958f512-2d99-4a3d-ac9b-49acffc297cb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labels',
            name='lab_id',
            field=models.UUIDField(default=uuid.UUID('8f2f42b1-b222-4c03-b763-be7361f195eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linksassociates',
            name='asc_id',
            field=models.UUIDField(default=uuid.UUID('ba3bfe58-d0ef-4944-8071-10b4c537b344'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='tsk_id',
            field=models.UUIDField(default=uuid.UUID('b8fc2c29-1445-4017-84db-8075f1154509'), editable=False, primary_key=True, serialize=False),
        ),
    ]
