# Generated by Django 5.2.8 on 2025-12-20 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Labels', '0003_initial'),
        ('Task', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fk_tsk_use_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='Labels.labels'),
        ),
        migrations.AddField(
            model_name='checklists',
            name='fk_che_tsk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
