# Generated by Django 5.2.8 on 2026-03-07 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_old_data', models.JSONField(blank=True, null=True)),
                ('log_new_data', models.JSONField(blank=True, null=True)),
                ('log_action', models.CharField(max_length=20)),
                ('log_object_id', models.CharField(max_length=50)),
                ('log_use_id', models.UUIDField(editable=False)),
                ('log_use_name', models.CharField(editable=False)),
                ('log_use_ip', models.GenericIPAddressField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_log_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
