# Generated by Django 5.2.8 on 2026-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRoles',
            fields=[
                ('tsr_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('tsr_name', models.CharField(max_length=30, unique=True)),
                ('tsr_description', models.CharField(max_length=255, null=True)),
                ('fk_tsr_scp_id', models.ManyToManyField(blank=True, to='Scope.scope')),
            ],
        ),
    ]
